# namePrefix: kustomize-

resources:
- deployment.yaml
- services.yaml
- client_id_sealed.yaml
- client_secret_sealed.yaml
- tenant_id_sealed.yaml
- mysql-deployment.yaml
# - zookeeper.yaml
# - kafka.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization