apiVersion: v1
kind: Service
metadata:
  name: sdl-go-service
spec:
  selector:
    app: sdl-go
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: zookeeper-service
#   name: zookeeper-service
# spec:
#   ports:
#     - name: zookeeper-port
#       port: 2181
#       targetPort: 2181
#   selector:
#     app: zookeeper
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: kafka-broker
#   name: kafka-service
# spec:
#   ports:
#     - port: 9092
#   selector:
#     app: kafka-broker
